/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSNotifyShadowAnimated;

/**
 *
 * @author JayJomJohn
 */
public class MainCRUD extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel model;
    
    public MainCRUD() {
        initComponents();
        conn=JavaConnector.ConnectDB();
        showDisable();
        showTable();
    }

private void showTable() {
    try {
        String[]title = {"ID","FIRSTNAME","MIDDLENAME","LASTNAME","GENDER","BIRTH","CONTACT","EMAIL","CITY"};

        String sql="SELECT * FROM tbl_crud";
        model=new DefaultTableModel(null,title);
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        String[]file = new String[9];

        while(rs.next()){
            file[0] = rs.getString("ID");
            file[1] = rs.getString("FIRSTNAME");
            file[2] = rs.getString("MIDDLENAME");
            file[3] = rs.getString("LASTNAME");
            file[4] = rs.getString("GENDER");
            file[5] = rs.getString("BIRTH");
            file[6] = rs.getString("CONTACT");
            file[7] = rs.getString("EMAIL");
            file[8] = rs.getString("CITY");
            
            model.addRow(file);
        }
        jTable1.setModel(model);
    }
    catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}    

    
private void showDisable(){
    //BUTTON
    CREATE.setEnabled(false);
    UPDATE.setEnabled(false);
    CLEAR.setEnabled(false);
    SEARCH.setEnabled(false);
    PRINT.setEnabled(false);
    DELETE.setEnabled(false);
    
    //TEXTFIELD
    txt_firstname.setEnabled(false);
    txt_lastname.setEnabled(false);
    txt_middlename.setEnabled(false);
    jRadioButton1_male.setEnabled(false);
    jRadioButton2_female.setEnabled(false);
    ((JTextField)txt_birth.getDateEditor().getUiComponent()).setEnabled(false);
    txt_contact.setEnabled(false);
    txt_email.setEnabled(false);
    txt_city.setEnabled(false);
   
}    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_middlename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1_male = new javax.swing.JRadioButton();
        jRadioButton2_female = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        DELETE = new javax.swing.JButton();
        CREATE = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        PRINT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_birth = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_city = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        NEW = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 648));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.setBorder(null);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 60, 204, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRUD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 12, 1164, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 48, 1164, 12));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 96, 204, 12));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 108, 120, 36));

        txt_firstname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_firstname.setBorder(null);
        jPanel1.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 108, 204, 36));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 144, 204, 12));

        txt_middlename.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_middlename.setBorder(null);
        jPanel1.add(txt_middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 156, 204, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Middle Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 156, 120, 36));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 192, 204, 12));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 204, 120, 36));

        txt_lastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_lastname.setBorder(null);
        jPanel1.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 204, 204, 36));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 240, 204, 12));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 252, 120, 30));

        jRadioButton1_male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1_male);
        jRadioButton1_male.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton1_male.setText("Male");
        jRadioButton1_male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jRadioButton1_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 252, 80, 30));

        jRadioButton2_female.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2_female);
        jRadioButton2_female.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2_female.setText("Female");
        jRadioButton2_female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jRadioButton2_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 252, 90, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 372, 1152, 12));

        DELETE.setBackground(new java.awt.Color(153, 0, 0));
        DELETE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("DELETE");
        DELETE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 324, 180, 36));

        CREATE.setBackground(new java.awt.Color(0, 51, 102));
        CREATE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CREATE.setForeground(new java.awt.Color(255, 255, 255));
        CREATE.setText("CREATE");
        CREATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CREATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEActionPerformed(evt);
            }
        });
        jPanel1.add(CREATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 324, 192, 36));

        UPDATE.setBackground(new java.awt.Color(51, 102, 0));
        UPDATE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setText("UPDATE");
        UPDATE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 324, 192, 36));

        PRINT.setBackground(new java.awt.Color(102, 0, 153));
        PRINT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PRINT.setForeground(new java.awt.Color(255, 255, 255));
        PRINT.setText("PRINT");
        PRINT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });
        jPanel1.add(PRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 324, 144, 36));

        SEARCH.setBackground(new java.awt.Color(0, 51, 51));
        SEARCH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SEARCH.setForeground(new java.awt.Color(255, 255, 255));
        SEARCH.setText("SEARCH");
        SEARCH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SEARCH.setFocusPainted(false);
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 60, 192, 36));

        CLEAR.setBackground(new java.awt.Color(102, 102, 102));
        CLEAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 255, 255));
        CLEAR.setText("CLEAR");
        CLEAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel1.add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 324, 192, 36));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Date of Birth:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 120, 36));

        txt_birth.setDateFormatString("yyyy-d-MM");
        txt_birth.setMaxSelectableDate(new java.util.Date(253370739669000L));
        txt_birth.setMinSelectableDate(new java.util.Date(631126869000L));
        jPanel1.add(txt_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 60, 204, 36));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("City:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 204, 120, 36));

        txt_contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_contact.setBorder(null);
        txt_contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactKeyTyped(evt);
            }
        });
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 108, 204, 36));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 144, 204, 12));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Contact:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 108, 120, 36));

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_email.setBorder(null);
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 156, 204, 36));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 192, 204, 12));

        txt_city.setColumns(20);
        txt_city.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_city.setRows(5);
        jScrollPane2.setViewportView(txt_city);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 204, 204, 72));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 156, 120, 36));

        NEW.setBackground(new java.awt.Color(0, 102, 102));
        NEW.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NEW.setForeground(new java.awt.Color(255, 255, 255));
        NEW.setText("NEW");
        NEW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NEW.setFocusPainted(false);
        NEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEWActionPerformed(evt);
            }
        });
        jPanel1.add(NEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 324, 192, 36));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(18);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 391, 1152, 240));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEWActionPerformed
      //BUTTON
       NEW.setEnabled(false);
       CREATE.setEnabled(true);
       CLEAR.setEnabled(true);
       
    //TEXTFIELD
    txt_firstname.requestFocus();
    txt_firstname.setEnabled(true);
    txt_lastname.setEnabled(true);
    txt_middlename.setEnabled(true);
    jRadioButton1_male.setEnabled(true);
    jRadioButton2_female.setEnabled(true);
    ((JTextField)txt_birth.getDateEditor().getUiComponent()).setEnabled(true);
    txt_contact.setEnabled(true);
    txt_email.setEnabled(true);
    txt_city.setEnabled(true);
    }//GEN-LAST:event_NEWActionPerformed

    private void txt_contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactKeyTyped
        String phonenum = txt_contact.getText();
        int length = phonenum.length();
        char c = evt.getKeyChar();        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9') {
            if(length<11) {            
            txt_contact.setEditable(true);
            }else{
            txt_contact.setEditable(false);
            getToolkit().beep();
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE) {
                txt_contact.setEditable(true);  
            }else{
                txt_contact.setEditable(false);
                getToolkit().beep();
            }
            
        }
    }//GEN-LAST:event_txt_contactKeyTyped

    private void CREATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEActionPerformed
    
    int x = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Add Record?","AddRecord",JOptionPane.YES_NO_OPTION);
    if(x==0){ 
    
        
        if(txt_firstname.getText().isEmpty()
                ||txt_lastname.getText().isEmpty()
                ||txt_middlename.getText().isEmpty()
                ||jRadioButton1_male.isSelected()==false && jRadioButton2_female.isSelected()==false
                ||((JTextField)txt_birth.getDateEditor().getUiComponent()).getText().isEmpty()
                ||txt_contact.getText().isEmpty()
                ||txt_email.getText().isEmpty()
                ||txt_city.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Complete Information","Missing Information",2);
new rojerusan.RSNotifyShadowAnimated("Complete Information!", "Missing Information!", 8,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.WARNING).setVisible(true);
                

        }else if(!Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$",txt_email.getText())){
//                JOptionPane.showMessageDialog(null, "Please enter a valid email","Error",JOptionPane.ERROR_MESSAGE);
        new rojerusan.RSNotifyShadowAnimated("Please Enter a Valid Email!", "Error!", 7,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.ERROR).setVisible(true);
        
        }else{
            
            try {
                String sql = "INSERT INTO tbl_crud(FIRSTNAME,MIDDLENAME,LASTNAME,GENDER,BIRTH,CONTACT,EMAIL,CITY)"
                        + "VALUES(?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_firstname.getText().toUpperCase());
                pst.setString(2,txt_middlename.getText().toUpperCase());
                pst.setString(3,txt_lastname.getText().toUpperCase());
                jRadioButton1_male.setActionCommand("Male");
                jRadioButton2_female.setActionCommand("Female");
                pst.setString(4,buttonGroup1.getSelection().getActionCommand());
                pst.setString(5,((JTextField)txt_birth.getDateEditor().getUiComponent()).getText());
                pst.setString(6,txt_contact.getText().toUpperCase());
                pst.setString(7,txt_email.getText());
                pst.setString(8,txt_city.getText().toUpperCase());
                pst.execute();
                new rojerusan.RSNotifyShadowAnimated("Add Record Success!", "Information Complete!", 6,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);
                
                showTable();
                UPDATE.setEnabled(true);
                CREATE.setEnabled(false);                
                SEARCH.setEnabled(true);
                txt_id.setEditable(true);
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        
        
        } 
        
               
        }
    }//GEN-LAST:event_CREATEActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
    
    int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","System message!",JOptionPane.OK_OPTION); 
    if (x == 0) {  
        
         if(txt_firstname.getText().isEmpty()
                ||txt_lastname.getText().isEmpty()
                ||txt_middlename.getText().isEmpty()
                ||jRadioButton1_male.isSelected()==false && jRadioButton2_female.isSelected()==false
                ||((JTextField)txt_birth.getDateEditor().getUiComponent()).getText().isEmpty()
                ||txt_contact.getText().isEmpty()
                ||txt_email.getText().isEmpty()
                ||txt_city.getText().isEmpty()){
//            JOptionPane.showMessageDialog(null,"Complete Information","Missing Information",2);
new rojerusan.RSNotifyShadowAnimated("Complete Information!", "Missing Information!", 6,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.ERROR).setVisible(true);
                

        }else if(!Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$",txt_email.getText())){
//            JOptionPane.showMessageDialog(null, "Please enter a valid email","Error",JOptionPane.ERROR_MESSAGE);
            new rojerusan.RSNotifyShadowAnimated("Please Enter a Valid Email!", "Error!", 7,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.ERROR).setVisible(true);
        
        }else{
            
            try {
                
                String sql = "UPDATE tbl_crud SET "
                        + "FIRSTNAME=?,"
                        + "MIDDLENAME=?,"
                        + "LASTNAME=?,"
                        + "GENDER=?,"
                        + "BIRTH=?,"
                        + "CONTACT=?,"
                        + "EMAIL=?,"
                        + "CITY=? WHERE ID='"+txt_id.getText()+"'";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_firstname.getText().toUpperCase());
                pst.setString(2,txt_middlename.getText().toUpperCase());
                pst.setString(3,txt_lastname.getText().toUpperCase());
                jRadioButton1_male.setActionCommand("Male");
                jRadioButton2_female.setActionCommand("Female");
                pst.setString(4,buttonGroup1.getSelection().getActionCommand());
                pst.setString(5,((JTextField)txt_birth.getDateEditor().getUiComponent()).getText());
                pst.setString(6,txt_contact.getText().toUpperCase());
                pst.setString(7,txt_email.getText());
                pst.setString(8,txt_city.getText().toUpperCase());
                pst.execute();
                new rojerusan.RSNotifyShadowAnimated("Update Record Success!", "Information Complete!", 6,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);
                
                showTable();
                UPDATE.setEnabled(false);
                DELETE.setEnabled(true);
                SEARCH.setEnabled(true);
                PRINT.setEnabled(true);
                txt_id.setEditable(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        
        
        } 
  
    }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          try{
            int row = jTable1.getSelectedRow();
            String Table_click=(jTable1.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM tbl_crud WHERE id='"+Table_click+"' ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()) {

                txt_id.setText(rs.getString("id"));
                txt_firstname.setText(rs.getString("firstname"));
                txt_lastname.setText(rs.getString("lastname"));
                txt_middlename.setText(rs.getString("middlename"));

                String gen = rs.getString("gender");
                if("Male".equals(gen)){
                    jRadioButton1_male.setSelected(true);
                }else if("Female".equals(gen)){
                    jRadioButton2_female.setSelected(true);
                }

                ((JTextField)txt_birth.getDateEditor().getUiComponent()).setText(rs.getString("birth"));
                txt_contact.setText(rs.getString("contact"));
                txt_email.setText(rs.getString("email"));
                txt_city.setText(rs.getString("city"));

            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
    txt_id.setText("");
    txt_firstname.setText("");
    txt_lastname.setText("");
    txt_middlename.setText("");
    buttonGroup1.clearSelection();
    ((JTextField)txt_birth.getDateEditor().getUiComponent()).setText("");
    txt_contact.setText("");
    txt_email.setText("");
    txt_city.setText("");
    
    }//GEN-LAST:event_CLEARActionPerformed

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed
      
        MessageFormat header = new MessageFormat("Report");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_PRINTActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
     if(!jTable1.getSelectionModel().isSelectionEmpty()){
    
    int p = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete?","DELETE",JOptionPane.YES_NO_OPTION);
    if(p==0){
      
       
        try{
            int row =jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            String sql ="DELETE FROM tbl_crud WHERE id="+value;
            pst=conn.prepareStatement(sql);         
            pst.executeUpdate();
            new rojerusan.RSNotifyShadowAnimated("Delete Record Success!", "Information Deleted!", 6,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.SUCCESS).setVisible(true);
            showTable();
            
            UPDATE.setEnabled(false);
            DELETE.setEnabled(false);
            CREATE.setEnabled(true);
            SEARCH.setEnabled(true);
            txt_id.setEditable(true);
            PRINT.setEnabled(true);
            
            }catch(SQLException e){
                   JOptionPane.showMessageDialog(this, e);   
        }        
        } 
    }
    }//GEN-LAST:event_DELETEActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
         
        
        try{          
         String sql = "SELECT * FROM tbl_crud WHERE id='"+txt_id.getText()+"'";            
         pst=conn.prepareCall(sql);
         rs=pst.executeQuery();
            if(rs.next()==false) {
                 new rojerusan.RSNotifyShadowAnimated("Record Not Found!", "Information Missing!", 6,RSNotifyShadowAnimated.PositionNotify.BottomLeft, RSNotifyShadowAnimated.AnimationNotify.BottomUp, RSNotifyShadowAnimated.TypeNotify.INFORMATION).setVisible(true);        
            }else{
                 txt_id.setText(rs.getString("id"));
                txt_firstname.setText(rs.getString("firstname"));
                txt_lastname.setText(rs.getString("lastname"));
                txt_middlename.setText(rs.getString("middlename"));

                String gen = rs.getString("gender");
                if("Male".equals(gen)){
                    jRadioButton1_male.setSelected(true);
                }else if("Female".equals(gen)){
                    jRadioButton2_female.setSelected(true);
                }

                ((JTextField)txt_birth.getDateEditor().getUiComponent()).setText(rs.getString("birth"));
                txt_contact.setText(rs.getString("contact"));
                txt_email.setText(rs.getString("email"));
                txt_city.setText(rs.getString("city"));
            }
            
        }catch(SQLException e) {
        JOptionPane.showMessageDialog(null, e);      
        } 
    }//GEN-LAST:event_SEARCHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }


            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton CREATE;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton NEW;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton SEARCH;
    private javax.swing.JButton UPDATE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1_male;
    private javax.swing.JRadioButton jRadioButton2_female;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser txt_birth;
    private javax.swing.JTextArea txt_city;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_middlename;
    // End of variables declaration//GEN-END:variables
}
